# 日频 AlphaMining：Colab A100 一体化训练流水线

本 Notebook 在一次 Colab 会话中依次完成：数据预处理 → 表达式检查 → GFlowNet 训练 → AlphaEval 筛选 → LightGBM 融合 → 训练产物打包下载。

RQAlphaPlus **不在 Colab 运行**。下载本 Notebook 生成的 `alphamining_colab_outputs.zip` 后，在本地使用 `06_rqalpha_backtest.ipynb` 回测。

## 1. 克隆仓库

默认克隆主仓库；目录已存在时自动把本地 `main` 快进到远端最新版，避免 Colab 继续使用旧模块。需要使用其他 fork 时，可预先设置环境变量 `ALPHAMINING_REPO_URL`。

In [1]:
from pathlib import Path
import os

if not Path('configs/training_config.yaml').exists():
    repo = os.environ.get(
        'ALPHAMINING_REPO_URL',
        'https://github.com/JacksonChiy/AlphaMining-GFlowNet-AlphaEval.git',
    )
    !git clone $repo
    %cd AlphaMining-GFlowNet-AlphaEval
else:
    !git checkout main
    !git pull --ff-only origin main

import importlib
importlib.invalidate_caches()
print('当前代码版本:')
!git rev-parse --short HEAD

Cloning into 'AlphaMining-GFlowNet-AlphaEval'...
remote: Enumerating objects: 391, done.
remote: Counting objects: 100% (391/391), done.
remote: Compressing objects: 100% (232/232), done.
remote: Total 391 (delta 225), reused 287 (delta 147), pack-reused 0 (from 0)
Receiving objects: 100% (391/391), 166.54 KiB | 11.89 MiB/s, done.
Resolving deltas: 100% (225/225), done.
/content/AlphaMining-GFlowNet-AlphaEval
当前代码版本:
9567498

## 2. 安装依赖

In [2]:
%pip install -q -r requirements.txt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 83.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 913.3/913.3 kB 58.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.5/77.5 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 136.8 MB/s eta 0:00:00

## 3. 检查 A100、CUDA 与显存

正式训练必须通过 A100 校验。

In [3]:
import torch

print('PyTorch 版本:', torch.__version__)
print('CUDA 状态:', torch.cuda.is_available())
print('CUDA 运行时:', torch.version.cuda)
assert torch.cuda.is_available(), '请在 Colab 中启用 NVIDIA A100 GPU 运行时'
gpu = torch.cuda.get_device_properties(0)
print('GPU 型号:', gpu.name)
print('GPU 显存（GB）:', round(gpu.total_memory / 1024**3, 2))
assert 'A100' in gpu.name.upper(), f'正式训练要求 A100；当前检测到 {gpu.name}'

PyTorch 版本: 2.11.0+cu128
CUDA 状态: True
CUDA 运行时: 12.8
GPU 型号: NVIDIA A100-SXM4-40GB
GPU 显存（GB）: 39.49

## 4. 加载配置

`FAST_MODE=True` 默认读取快速训练配置：使用 2020–2023 年挖掘、筛选和建立初始融合模型，在包含历史预热期的 2020–2026 数据上计算因子，并只输出 2024–2026 年的样本外预测用于本地回测。确认流程可运行后，改为 `False` 即切换到全量正式配置。

In [4]:
import yaml
from src.utils import validate_research_date_split

FAST_MODE = False
REUSE_EXISTING_ALPHA_POOL = False
CONFIG_PATH = ('configs/quick_training_config.yaml' if FAST_MODE
               else 'configs/training_config.yaml')
DOWNLOAD_OUTPUTS = True

with open(CONFIG_PATH, encoding='utf-8') as file:
    config = yaml.safe_load(file)
POOL_SIZE = int(config.get('pipeline', {}).get('pool_size', 100))
print('训练模式:', '快速' if FAST_MODE else '正式全量')
print('配置:', CONFIG_PATH, '因子池:', POOL_SIZE)
print('日期切分:', validate_research_date_split(config))
config

训练模式: 正式全量
配置: configs/training_config.yaml 因子池: 100
日期切分: {'training': '2020-01-01..2023-12-31', 'out_of_sample': '2024-01-01..2026-12-31'}

{'dataset': {'file': 'data/price.csv',
  'output': 'data/daily_price.pkl',
  'horizon': 5,
  'required_columns': ['date',
   'code',
   'open',
   'high',
   'low',
   'close',
   'volume'],
  'start_date': '2020-01-01',
  'end_date': '2026-12-31',
  'mining_start_date': '2020-01-01',
  'mining_end_date': '2023-12-31',
  'out_of_sample_start_date': '2024-01-01',
  'out_of_sample_end_date': '2026-12-31',
  'chunksize': 500000},
 'model': {'name': 'GFlowNet',
  'hidden_dim': 256,
  'num_layers': 4,
  'num_heads': 8,
  'dropout': 0.1,
  'max_sequence_length': 32},
 'training': {'epochs': 100,
  'trajectories_per_epoch': 32,
  'learning_rate': 0.0001,
  'weight_decay': 0.0001,
  'reward_temperature': 1.0,
  'mixed_precision': True,
  'reward_workers': 4,
  'seed': 42},
 'reward': {'top_quantile': 0.1,
  'horizon': 5,
  'risk_aversion': 1.0,
  'min_cross_section': 20,
  'min_coverage': 0.8,
  'coverage_penalty_power': 2.0},
 'alpha_eval': {'rolling_window': 60,
  'perturbation_std': 0.05,
  'dpp_k': 50,
  'dpp_max_rows': 500000,
  'verbose': True,
  'seed': 42},
 'lightgbm': {'horizon': 5,
  'train_window_days': 1008,
  'min_train_days': 756,
  'refit_interval_days': 20,
  'num_leaves': 31,
  'learning_rate': 0.03,
  'n_estimators': 500,
  'seed': 42,
  'prediction_start_date': '2024-01-01',
  'prediction_end_date': '2026-12-31'},
 'backtest': {'initial_cash': 1000000,
  'benchmark': '000300.XSHG',
  'top_n': 30,
  'rebalance_days': 5,
  'slippage': 0.001},
 'pipeline': {'pool_size': 100}}

## 5. 从 Google Drive 复制 `price.csv`

把行情文件放在 Google Drive 的 `MyDrive/price.csv`。挂载 Drive 后，代码按文件大小判断是否需要复制到 Colab 本地高速磁盘。代码不会调用外部行情接口。

In [5]:
from google.colab import drive
drive.mount('/content/drive')

import shutil

PRICE_CSV_DRIVE = Path('/content/drive/MyDrive/price.csv')
PRICE_CSV_LOCAL = Path('data/price.csv')
PRICE_CSV_LOCAL.parent.mkdir(parents=True, exist_ok=True)
if not PRICE_CSV_DRIVE.exists():
    raise FileNotFoundError(f'Google Drive 中没有找到: {PRICE_CSV_DRIVE}')
if (not PRICE_CSV_LOCAL.exists() or
        PRICE_CSV_LOCAL.stat().st_size != PRICE_CSV_DRIVE.stat().st_size):
    print('复制price.csv到Colab本地，请等待...')
    shutil.copy2(PRICE_CSV_DRIVE, PRICE_CSV_LOCAL)
config['dataset']['file'] = str(PRICE_CSV_LOCAL)
print('local csv MB =', round(PRICE_CSV_LOCAL.stat().st_size / 1024**2, 1))

Mounted at /content/drive
复制price.csv到Colab本地，请等待...
local csv MB = 700.7

## 6. 数据预处理

自动完成字段映射、日期转换、排序、缺失与异常处理、可选复权及同日截面标准化，生成 `data/daily_price.pkl`。

In [6]:
import json
from src.data_loader import prepare_price_csv

dataset_filter_keys = (
    'start_date', 'end_date', 'max_stocks', 'universe_start_date',
    'universe_end_date', 'chunksize',
)
dataset_filters = {
    key: config['dataset'][key]
    for key in dataset_filter_keys
    if config['dataset'].get(key) is not None
}
daily = prepare_price_csv(
    config['dataset']['file'],
    config['dataset']['output'],
    'results/data_quality_report.json',
    **dataset_filters,
)
display(daily.head())
print('行数:', len(daily), '交易日数:', daily.date.nunique(), '股票数:', daily.code.nunique())
display(json.loads(Path('results/data_quality_report.json').read_text(encoding='utf-8')))

[Data] filtered_read_start chunksize=500000
[Data] filtered_read_chunk=001 source_rows=500,000 kept_rows=500,000
[Data] filtered_read_chunk=002 source_rows=1,000,000 kept_rows=1,000,000
[Data] filtered_read_chunk=003 source_rows=1,500,000 kept_rows=1,500,000
[Data] filtered_read_chunk=004 source_rows=2,000,000 kept_rows=2,000,000
[Data] filtered_read_chunk=005 source_rows=2,500,000 kept_rows=2,500,000
[Data] filtered_read_chunk=006 source_rows=3,000,000 kept_rows=3,000,000
[Data] filtered_read_chunk=007 source_rows=3,500,000 kept_rows=3,500,000
[Data] filtered_read_chunk=008 source_rows=4,000,000 kept_rows=4,000,000
[Data] filtered_read_chunk=009 source_rows=4,500,000 kept_rows=4,500,000
[Data] filtered_read_chunk=010 source_rows=5,000,000 kept_rows=5,000,000
[Data] filtered_read_chunk=011 source_rows=5,500,000 kept_rows=5,500,000
[Data] filtered_read_chunk=012 source_rows=6,000,000 kept_rows=6,000,000
[Data] filtered_read_chunk=013 source_rows=6,500,000 kept_rows=6,500,000
[Data] filtered_read_chunk=014 source_rows=7,000,000 kept_rows=7,000,000
[Data] filtered_read_chunk=015 source_rows=7,332,011 kept_rows=7,332,011
[Data] filtered_read_complete source_rows=7,332,011 kept_rows=7,332,011

,date,code,open,high,low,close,volume,amount,vwap,z_open,z_high,z_low,z_close,z_volume,z_vwap
0,2020-01-02,000001.XSHE,13.0826,13.3183,13.0040,13.2555,153023187.0,2.571196e+09,16.802659,0.086548,0.080455,0.090860,0.087381,3.944691,0.262765
1,2020-01-02,000002.XSHE,26.7856,27.4389,26.5488,26.5896,101213040.0,3.342374e+09,33.023155,1.094384,1.092277,1.100818,1.059321,2.410905,1.358297
2,2020-01-02,000006.XSHE,4.8330,4.8508,4.7796,4.8063,12475176.0,6.745286e+07,5.406967,-0.520198,-0.526290,-0.522386,-0.528492,-0.216087,-0.506900
3,2020-01-02,000007.XSHE,9.5600,9.5800,9.4400,9.5500,3744697.0,3.569469e+07,9.532063,-0.172534,-0.187415,-0.174887,-0.182718,-0.474544,-0.228291
4,2020-01-02,000008.XSHE,3.6480,3.6978,3.6280,3.6978,37746790.0,1.392082e+08,3.687947,-0.607353,-0.608909,-0.608255,-0.609292,0.532053,-0.623003

行数: 7332011 交易日数: 1583 股票数: 5200

{'input_rows': 7332011,
 'source_rows_scanned': 7332011,
 'output_rows': 7332011,
 'column_mapping': {'date': 'date',
  'order_book_id': 'code',
  'open': 'open',
  'high': 'high',
  'low': 'low',
  'close': 'close',
  'volume': 'volume',
  'total_turnover': 'amount'},
 'duplicate_rows_removed': 0,
 'invalid_rows_removed': 0,
 'missing_by_column': {'date': 0,
  'code': 0,
  'open': 0,
  'high': 0,
  'low': 0,
  'close': 0,
  'volume': 0,
  'amount': 0,
  'vwap': 613,
  'z_open': 0,
  'z_high': 0,
  'z_low': 0,
  'z_close': 0,
  'z_volume': 0,
  'z_vwap': 0},
 'outliers_clipped': {'open': 16333,
  'high': 16340,
  'low': 16347,
  'close': 16342,
  'vwap': 17079,
  'volume': 11603,
  'amount': 11603},
 'adjustment_applied': False,
 'risk_fields_available': {'industry': False, 'market_cap': False},
 'date_filter': {'start_date': '2020-01-01', 'end_date': '2026-12-31'},
 'universe_selection': {}}

## 7. 表达式引擎检查

随机生成并执行 10 个表达式，确认复杂度、深度和有效值覆盖率。

In [7]:
import pandas as pd
from src.expression import Expression

expression_rows = []
for seed in range(10):
    expression = Expression.generate(max_depth=4, seed=seed)
    values = expression.execute(daily)
    expression_rows.append({
        'expression': str(expression),
        'complexity': expression.complexity(),
        'depth': expression.depth(),
        'coverage': round(values.notna().mean(), 4),
    })
display(pd.DataFrame(expression_rows))

                      expression  complexity  depth  coverage
0              ts_max(volume,40)           2      2    0.9724
1                           open           1      1    1.0000
2                   cs_rank(low)           2      2    1.0000
3                         volume           1      1    1.0000
4                           open           1      1    1.0000
5            ts_zscore(close,10)           2      2    0.9932
6  cs_zscore(abs(ts_sum(low,5)))           4      4    0.9972
7                    log(volume)           2      2    1.0000
8                          close           1      1    1.0000
9               sub(vwap,volume)           3      2    0.9999

## 8. GFlowNet A100 混合精度训练

训练使用 Trajectory Balance Loss，开启 A100 混合精度和 TF32，并对同一 epoch 的轨迹执行批量 Transformer 推理；Reward 按配置使用多线程并行，RankIC、LongIR 与风险暴露使用向量化计算。覆盖率同时检查有效观测与有效交易日占比，低覆盖表达式会被降权，低于配置门槛的表达式不会进入因子池。每条训练轨迹仍会输出完整进度，但 GPU 指标按 epoch 批量传回 CPU，减少同步等待。

In [ ]:
from src.gflownet.factor_pool import execute_saved_alpha_pool
from src.gflownet.run_training import run as run_gflownet
from src.utils import create_experiment, slice_date_range

reuse_alpha_pool = (REUSE_EXISTING_ALPHA_POOL and
                    Path('results/alpha_pool.csv').exists())
if reuse_alpha_pool:
    print('检测到已有 Alpha Pool：跳过 GFlowNet 训练，直接在完整行情上重算因子。')
    experiment_dir = create_experiment(CONFIG_PATH)
    execute_saved_alpha_pool(
        daily,
        oos_start_date=config['dataset'].get('out_of_sample_start_date'),
        oos_end_date=config['dataset'].get('out_of_sample_end_date'),
    )
else:
    experiment_dir = run_gflownet(
        CONFIG_PATH, require_a100=True, pool_size=POOL_SIZE
    )
print('实验目录:', experiment_dir.resolve())
if Path('results/gflownet_training_metrics.csv').exists():
    display(pd.read_csv('results/gflownet_training_metrics.csv').tail())
if Path('results/gflownet_trajectory_metrics.csv').exists():
    display(pd.read_csv('results/gflownet_trajectory_metrics.csv').tail(32))
display(pd.read_csv('results/alpha_pool.csv').head(20))

## 9. 检查点重载测试

In [ ]:
from src.gflownet import GFlowNetTrainer, RewardEvaluator

if Path('checkpoints/gflownet_best.pt').exists():
    mining_daily_for_reload = slice_date_range(
        daily, config['dataset'].get('mining_start_date'),
        config['dataset'].get('mining_end_date'), label='检查点样本内行情',
    )
    reward_evaluator = RewardEvaluator(mining_daily_for_reload, **config['reward'])
    loaded_trainer = GFlowNetTrainer.load_checkpoint(
        'checkpoints/gflownet_best.pt', reward_evaluator, device='cuda'
    )
    sample_expression, _, sample_tokens = loaded_trainer.sample_trajectory(greedy=True)
    print('检查点重载成功:', sample_expression)
    print('Token 序列:', sample_tokens)
else:
    print('本次仅复用 Alpha Pool，未提供 GFlowNet checkpoint，跳过重载测试。')
assert Path('results/alpha_pool.csv').exists()
assert Path('results/alpha_factor_matrix.pkl').exists()

## 10. AlphaEval 因子评价与 DPP 筛选

标签统一为 `close(t+5) / close(t+1) - 1`。

In [8]:
!cp /content/drive/MyDrive/results.zip /content/AlphaMining-GFlowNet-AlphaEval
!unzip results.zip

Archive:  results.zip
  inflating: results/alpha_pool.csv
  inflating: results/alpha_factor_matrix.pkl
replace results/data_quality_report.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: results/data_quality_report.json
  inflating: results/gflownet_trajectory_metrics.csv
  inflating: results/gflownet_training_metrics.csv
  inflating: results/alpha_factor_matrix_oos.pkl

In [10]:
import shutil
from src.alpha_eval import AlphaEval, AlphaEvalConfig
from src.utils import slice_date_range

factor_matrix = pd.read_pickle('results/alpha_factor_matrix.pkl')
factor_metadata = pd.read_csv('results/alpha_pool.csv')
alpha_eval_values = dict(config['alpha_eval'])
alpha_eval_values['horizon'] = config['dataset']['horizon']
mining_daily = slice_date_range(
    daily, config['dataset'].get('mining_start_date'),
    config['dataset'].get('mining_end_date'), label='AlphaEval 行情',
)
mining_factor_matrix = slice_date_range(
    factor_matrix, config['dataset'].get('mining_start_date'),
    config['dataset'].get('mining_end_date'), label='AlphaEval 因子',
)
print('AlphaEval 样本内区间:', mining_daily.date.min(), '至', mining_daily.date.max())
alpha_eval = AlphaEval(
    mining_daily, mining_factor_matrix, AlphaEvalConfig(**alpha_eval_values)
)
evaluation = alpha_eval.evaluate(factor_metadata)
selected_factors = evaluation.loc[evaluation['dpp_selected'].astype(bool), 'factor'].tolist()
shutil.copy2('results/alpha_eval_result.csv', experiment_dir / 'alpha_eval_result.csv')
print('DPP 选中因子数:', len(selected_factors))
display(evaluation.head(30))

AlphaEval 样本内区间: 2020-01-02 00:00:00 至 2023-12-29 00:00:00
[AlphaEval] 开始评价：样本=4,207,027，交易日=970，因子=100
[AlphaEval] 因子 1/100 factor_001：开始
[AlphaEval] 因子 1/100 factor_001 [1/4] IC/RankIC 完成 (1.7s)
[AlphaEval] 因子 1/100 factor_001 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 1/100 factor_001 [3/4] 扰动鲁棒性完成 (1.9s)
[AlphaEval] 因子 1/100 factor_001 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 1/100 factor_001：完成，耗时=7.1s，总进度=1.0%，预计剩余=11.7min
[AlphaEval] 因子 2/100 factor_002：开始
[AlphaEval] 因子 2/100 factor_002 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 2/100 factor_002 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 2/100 factor_002 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 2/100 factor_002 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 2/100 factor_002：完成，耗时=9.5s，总进度=2.0%，预计剩余=13.5min
[AlphaEval] 因子 3/100 factor_003：开始
[AlphaEval] 因子 3/100 factor_003 [1/4] IC/RankIC 完成 (2.9s)
[AlphaEval] 因子 3/100 factor_003 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 3/100 factor_003 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 3/100 factor_003 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 3/100 factor_003：完成，耗时=9.4s，总进度=3.0%，预计剩余=14.0min
[AlphaEval] 因子 4/100 factor_004：开始
[AlphaEval] 因子 4/100 factor_004 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 4/100 factor_004 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 4/100 factor_004 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 4/100 factor_004 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 4/100 factor_004：完成，耗时=9.6s，总进度=4.0%，预计剩余=14.2min
[AlphaEval] 因子 5/100 factor_005：开始
[AlphaEval] 因子 5/100 factor_005 [1/4] IC/RankIC 完成 (2.7s)
[AlphaEval] 因子 5/100 factor_005 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 5/100 factor_005 [3/4] 扰动鲁棒性完成 (2.8s)
[AlphaEval] 因子 5/100 factor_005 [4/4] 排名稳定性完成 (2.6s)
[AlphaEval] 因子 5/100 factor_005：完成，耗时=8.8s，总进度=5.0%，预计剩余=14.0min
[AlphaEval] 因子 6/100 factor_006：开始
[AlphaEval] 因子 6/100 factor_006 [1/4] IC/RankIC 完成 (3.2s)
[AlphaEval] 因子 6/100 factor_006 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 6/100 factor_006 [3/4] 扰动鲁棒性完成 (3.3s)
[AlphaEval] 因子 6/100 factor_006 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 6/100 factor_006：完成，耗时=10.1s，总进度=6.0%，预计剩余=14.2min
[AlphaEval] 因子 7/100 factor_007：开始
[AlphaEval] 因子 7/100 factor_007 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 7/100 factor_007 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 7/100 factor_007 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 7/100 factor_007 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 7/100 factor_007：完成，耗时=9.8s，总进度=7.0%，预计剩余=14.2min
[AlphaEval] 因子 8/100 factor_008：开始
[AlphaEval] 因子 8/100 factor_008 [1/4] IC/RankIC 完成 (2.7s)
[AlphaEval] 因子 8/100 factor_008 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 8/100 factor_008 [3/4] 扰动鲁棒性完成 (2.7s)
[AlphaEval] 因子 8/100 factor_008 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 8/100 factor_008：完成，耗时=8.8s，总进度=8.0%，预计剩余=14.0min
[AlphaEval] 因子 9/100 factor_009：开始
[AlphaEval] 因子 9/100 factor_009 [1/4] IC/RankIC 完成 (2.9s)
[AlphaEval] 因子 9/100 factor_009 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 9/100 factor_009 [3/4] 扰动鲁棒性完成 (2.9s)
[AlphaEval] 因子 9/100 factor_009 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 9/100 factor_009：完成，耗时=9.2s，总进度=9.0%，预计剩余=13.8min
[AlphaEval] 因子 10/100 factor_010：开始
[AlphaEval] 因子 10/100 factor_010 [1/4] IC/RankIC 完成 (3.2s)
[AlphaEval] 因子 10/100 factor_010 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 10/100 factor_010 [3/4] 扰动鲁棒性完成 (3.3s)
[AlphaEval] 因子 10/100 factor_010 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 10/100 factor_010：完成，耗时=10.1s，总进度=10.0%，预计剩余=13.8min
[AlphaEval] 因子 11/100 factor_011：开始
[AlphaEval] 因子 11/100 factor_011 [1/4] IC/RankIC 完成 (2.7s)
[AlphaEval] 因子 11/100 factor_011 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 11/100 factor_011 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 11/100 factor_011 [4/4] 排名稳定性完成 (2.5s)
[AlphaEval] 因子 11/100 factor_011：完成，耗时=9.0s，总进度=11.0%，预计剩余=13.6min
[AlphaEval] 因子 12/100 factor_012：开始
[AlphaEval] 因子 12/100 factor_012 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 12/100 factor_012 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 12/100 factor_012 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 12/100 factor_012 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 12/100 factor_012：完成，耗时=9.4s，总进度=12.0%，预计剩余=13.5min
[AlphaEval] 因子 13/100 factor_013：开始
[AlphaEval] 因子 13/100 factor_013 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 13/100 factor_013 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 13/100 factor_013 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 13/100 factor_013 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 13/100 factor_013：完成，耗时=9.4s，总进度=13.0%，预计剩余=13.4min
[AlphaEval] 因子 14/100 factor_014：开始
[AlphaEval] 因子 14/100 factor_014 [1/4] IC/RankIC 完成 (3.2s)
[AlphaEval] 因子 14/100 factor_014 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 14/100 factor_014 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 14/100 factor_014 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 14/100 factor_014：完成，耗时=10.0s，总进度=14.0%，预计剩余=13.3min
[AlphaEval] 因子 15/100 factor_015：开始
[AlphaEval] 因子 15/100 factor_015 [1/4] IC/RankIC 完成 (3.2s)
[AlphaEval] 因子 15/100 factor_015 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 15/100 factor_015 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 15/100 factor_015 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 15/100 factor_015：完成，耗时=9.9s，总进度=15.0%，预计剩余=13.2min
[AlphaEval] 因子 16/100 factor_016：开始
[AlphaEval] 因子 16/100 factor_016 [1/4] IC/RankIC 完成 (2.8s)
[AlphaEval] 因子 16/100 factor_016 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 16/100 factor_016 [3/4] 扰动鲁棒性完成 (2.8s)
[AlphaEval] 因子 16/100 factor_016 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 16/100 factor_016：完成，耗时=8.9s，总进度=16.0%，预计剩余=13.0min
[AlphaEval] 因子 17/100 factor_017：开始
[AlphaEval] 因子 17/100 factor_017 [1/4] IC/RankIC 完成 (1.7s)
[AlphaEval] 因子 17/100 factor_017 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 17/100 factor_017 [3/4] 扰动鲁棒性完成 (1.9s)
[AlphaEval] 因子 17/100 factor_017 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 17/100 factor_017：完成，耗时=7.0s，总进度=17.0%，预计剩余=12.7min
[AlphaEval] 因子 18/100 factor_018：开始
[AlphaEval] 因子 18/100 factor_018 [1/4] IC/RankIC 完成 (1.8s)
[AlphaEval] 因子 18/100 factor_018 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 18/100 factor_018 [3/4] 扰动鲁棒性完成 (1.9s)
[AlphaEval] 因子 18/100 factor_018 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 18/100 factor_018：完成，耗时=7.1s，总进度=18.0%，预计剩余=12.4min
[AlphaEval] 因子 19/100 factor_019：开始
[AlphaEval] 因子 19/100 factor_019 [1/4] IC/RankIC 完成 (3.3s)
[AlphaEval] 因子 19/100 factor_019 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 19/100 factor_019 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 19/100 factor_019 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 19/100 factor_019：完成，耗时=9.9s，总进度=19.0%，预计剩余=12.3min
[AlphaEval] 因子 20/100 factor_020：开始
[AlphaEval] 因子 20/100 factor_020 [1/4] IC/RankIC 完成 (1.8s)
[AlphaEval] 因子 20/100 factor_020 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 20/100 factor_020 [3/4] 扰动鲁棒性完成 (1.9s)
[AlphaEval] 因子 20/100 factor_020 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 20/100 factor_020：完成，耗时=7.1s，总进度=20.0%，预计剩余=12.0min
[AlphaEval] 因子 21/100 factor_021：开始
[AlphaEval] 因子 21/100 factor_021 [1/4] IC/RankIC 完成 (2.7s)
[AlphaEval] 因子 21/100 factor_021 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 21/100 factor_021 [3/4] 扰动鲁棒性完成 (2.8s)
[AlphaEval] 因子 21/100 factor_021 [4/4] 排名稳定性完成 (2.6s)
[AlphaEval] 因子 21/100 factor_021：完成，耗时=8.8s，总进度=21.0%，预计剩余=11.8min
[AlphaEval] 因子 22/100 factor_022：开始
[AlphaEval] 因子 22/100 factor_022 [1/4] IC/RankIC 完成 (3.2s)
[AlphaEval] 因子 22/100 factor_022 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 22/100 factor_022 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 22/100 factor_022 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 22/100 factor_022：完成，耗时=9.9s，总进度=22.0%，预计剩余=11.7min
[AlphaEval] 因子 23/100 factor_023：开始
[AlphaEval] 因子 23/100 factor_023 [1/4] IC/RankIC 完成 (1.8s)
[AlphaEval] 因子 23/100 factor_023 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 23/100 factor_023 [3/4] 扰动鲁棒性完成 (1.9s)
[AlphaEval] 因子 23/100 factor_023 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 23/100 factor_023：完成，耗时=7.1s，总进度=23.0%，预计剩余=11.5min
[AlphaEval] 因子 24/100 factor_024：开始
[AlphaEval] 因子 24/100 factor_024 [1/4] IC/RankIC 完成 (1.9s)
[AlphaEval] 因子 24/100 factor_024 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 24/100 factor_024 [3/4] 扰动鲁棒性完成 (1.8s)
[AlphaEval] 因子 24/100 factor_024 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 24/100 factor_024：完成，耗时=7.3s，总进度=24.0%，预计剩余=11.2min
[AlphaEval] 因子 25/100 factor_025：开始
[AlphaEval] 因子 25/100 factor_025 [1/4] IC/RankIC 完成 (1.8s)
[AlphaEval] 因子 25/100 factor_025 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 25/100 factor_025 [3/4] 扰动鲁棒性完成 (1.9s)
[AlphaEval] 因子 25/100 factor_025 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 25/100 factor_025：完成，耗时=7.1s，总进度=25.0%，预计剩余=11.0min
[AlphaEval] 因子 26/100 factor_026：开始
[AlphaEval] 因子 26/100 factor_026 [1/4] IC/RankIC 完成 (2.9s)
[AlphaEval] 因子 26/100 factor_026 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 26/100 factor_026 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 26/100 factor_026 [4/4] 排名稳定性完成 (2.5s)
[AlphaEval] 因子 26/100 factor_026：完成，耗时=9.3s，总进度=26.0%，预计剩余=10.9min
[AlphaEval] 因子 27/100 factor_027：开始
[AlphaEval] 因子 27/100 factor_027 [1/4] IC/RankIC 完成 (3.2s)
[AlphaEval] 因子 27/100 factor_027 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 27/100 factor_027 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 27/100 factor_027 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 27/100 factor_027：完成，耗时=9.8s，总进度=27.0%，预计剩余=10.8min
[AlphaEval] 因子 28/100 factor_028：开始
[AlphaEval] 因子 28/100 factor_028 [1/4] IC/RankIC 完成 (3.3s)
[AlphaEval] 因子 28/100 factor_028 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 28/100 factor_028 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 28/100 factor_028 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 28/100 factor_028：完成，耗时=10.0s，总进度=28.0%，预计剩余=10.7min
[AlphaEval] 因子 29/100 factor_029：开始
[AlphaEval] 因子 29/100 factor_029 [1/4] IC/RankIC 完成 (2.5s)
[AlphaEval] 因子 29/100 factor_029 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 29/100 factor_029 [3/4] 扰动鲁棒性完成 (2.7s)
[AlphaEval] 因子 29/100 factor_029 [4/4] 排名稳定性完成 (2.3s)
[AlphaEval] 因子 29/100 factor_029：完成，耗时=8.1s，总进度=29.0%，预计剩余=10.5min
[AlphaEval] 因子 30/100 factor_030：开始
[AlphaEval] 因子 30/100 factor_030 [1/4] IC/RankIC 完成 (3.2s)
[AlphaEval] 因子 30/100 factor_030 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 30/100 factor_030 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 30/100 factor_030 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 30/100 factor_030：完成，耗时=9.9s，总进度=30.0%，预计剩余=10.4min
[AlphaEval] 因子 31/100 factor_031：开始
[AlphaEval] 因子 31/100 factor_031 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 31/100 factor_031 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 31/100 factor_031 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 31/100 factor_031 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 31/100 factor_031：完成，耗时=9.8s，总进度=31.0%，预计剩余=10.3min
[AlphaEval] 因子 32/100 factor_032：开始
[AlphaEval] 因子 32/100 factor_032 [1/4] IC/RankIC 完成 (3.3s)
[AlphaEval] 因子 32/100 factor_032 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 32/100 factor_032 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 32/100 factor_032 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 32/100 factor_032：完成，耗时=10.1s，总进度=32.0%，预计剩余=10.2min
[AlphaEval] 因子 33/100 factor_033：开始
[AlphaEval] 因子 33/100 factor_033 [1/4] IC/RankIC 完成 (3.3s)
[AlphaEval] 因子 33/100 factor_033 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 33/100 factor_033 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 33/100 factor_033 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 33/100 factor_033：完成，耗时=10.2s，总进度=33.0%，预计剩余=10.1min
[AlphaEval] 因子 34/100 factor_034：开始
[AlphaEval] 因子 34/100 factor_034 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 34/100 factor_034 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 34/100 factor_034 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 34/100 factor_034 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 34/100 factor_034：完成，耗时=9.6s，总进度=34.0%，预计剩余=9.9min
[AlphaEval] 因子 35/100 factor_035：开始
[AlphaEval] 因子 35/100 factor_035 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 35/100 factor_035 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 35/100 factor_035 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 35/100 factor_035 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 35/100 factor_035：完成，耗时=9.7s，总进度=35.0%，预计剩余=9.8min
[AlphaEval] 因子 36/100 factor_036：开始
[AlphaEval] 因子 36/100 factor_036 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 36/100 factor_036 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 36/100 factor_036 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 36/100 factor_036 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 36/100 factor_036：完成，耗时=9.5s，总进度=36.0%，预计剩余=9.7min
[AlphaEval] 因子 37/100 factor_037：开始
[AlphaEval] 因子 37/100 factor_037 [1/4] IC/RankIC 完成 (3.3s)
[AlphaEval] 因子 37/100 factor_037 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 37/100 factor_037 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 37/100 factor_037 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 37/100 factor_037：完成，耗时=10.0s，总进度=37.0%，预计剩余=9.5min
[AlphaEval] 因子 38/100 factor_038：开始
[AlphaEval] 因子 38/100 factor_038 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 38/100 factor_038 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 38/100 factor_038 [3/4] 扰动鲁棒性完成 (3.3s)
[AlphaEval] 因子 38/100 factor_038 [4/4] 排名稳定性完成 (2.6s)
[AlphaEval] 因子 38/100 factor_038：完成，耗时=9.6s，总进度=38.0%，预计剩余=9.4min
[AlphaEval] 因子 39/100 factor_039：开始
[AlphaEval] 因子 39/100 factor_039 [1/4] IC/RankIC 完成 (2.4s)
[AlphaEval] 因子 39/100 factor_039 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 39/100 factor_039 [3/4] 扰动鲁棒性完成 (2.7s)
[AlphaEval] 因子 39/100 factor_039 [4/4] 排名稳定性完成 (2.3s)
[AlphaEval] 因子 39/100 factor_039：完成，耗时=8.1s，总进度=39.0%，预计剩余=9.2min
[AlphaEval] 因子 40/100 factor_040：开始
[AlphaEval] 因子 40/100 factor_040 [1/4] IC/RankIC 完成 (2.9s)
[AlphaEval] 因子 40/100 factor_040 [2/4] Top组合 Sharpe 完成 (0.5s)
[AlphaEval] 因子 40/100 factor_040 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 40/100 factor_040 [4/4] 排名稳定性完成 (2.5s)
[AlphaEval] 因子 40/100 factor_040：完成，耗时=9.3s，总进度=40.0%，预计剩余=9.1min
[AlphaEval] 因子 41/100 factor_041：开始
[AlphaEval] 因子 41/100 factor_041 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 41/100 factor_041 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 41/100 factor_041 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 41/100 factor_041 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 41/100 factor_041：完成，耗时=9.3s，总进度=41.0%，预计剩余=8.9min
[AlphaEval] 因子 42/100 factor_042：开始
[AlphaEval] 因子 42/100 factor_042 [1/4] IC/RankIC 完成 (2.9s)
[AlphaEval] 因子 42/100 factor_042 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 42/100 factor_042 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 42/100 factor_042 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 42/100 factor_042：完成，耗时=9.3s，总进度=42.0%，预计剩余=8.8min
[AlphaEval] 因子 43/100 factor_043：开始
[AlphaEval] 因子 43/100 factor_043 [1/4] IC/RankIC 完成 (2.8s)
[AlphaEval] 因子 43/100 factor_043 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 43/100 factor_043 [3/4] 扰动鲁棒性完成 (2.9s)
[AlphaEval] 因子 43/100 factor_043 [4/4] 排名稳定性完成 (2.6s)
[AlphaEval] 因子 43/100 factor_043：完成，耗时=9.0s，总进度=43.0%，预计剩余=8.6min
[AlphaEval] 因子 44/100 factor_044：开始
[AlphaEval] 因子 44/100 factor_044 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 44/100 factor_044 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 44/100 factor_044 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 44/100 factor_044 [4/4] 排名稳定性完成 (2.6s)
[AlphaEval] 因子 44/100 factor_044：完成，耗时=9.6s，总进度=44.0%，预计剩余=8.5min
[AlphaEval] 因子 45/100 factor_045：开始
[AlphaEval] 因子 45/100 factor_045 [1/4] IC/RankIC 完成 (2.5s)
[AlphaEval] 因子 45/100 factor_045 [2/4] Top组合 Sharpe 完成 (0.5s)
[AlphaEval] 因子 45/100 factor_045 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 45/100 factor_045 [4/4] 排名稳定性完成 (2.0s)
[AlphaEval] 因子 45/100 factor_045：完成，耗时=8.4s，总进度=45.0%，预计剩余=8.3min
[AlphaEval] 因子 46/100 factor_046：开始
[AlphaEval] 因子 46/100 factor_046 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 46/100 factor_046 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 46/100 factor_046 [3/4] 扰动鲁棒性完成 (2.9s)
[AlphaEval] 因子 46/100 factor_046 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 46/100 factor_046：完成，耗时=9.3s，总进度=46.0%，预计剩余=8.2min
[AlphaEval] 因子 47/100 factor_047：开始
[AlphaEval] 因子 47/100 factor_047 [1/4] IC/RankIC 完成 (2.9s)
[AlphaEval] 因子 47/100 factor_047 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 47/100 factor_047 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 47/100 factor_047 [4/4] 排名稳定性完成 (2.6s)
[AlphaEval] 因子 47/100 factor_047：完成，耗时=9.2s，总进度=47.0%，预计剩余=8.0min
[AlphaEval] 因子 48/100 factor_048：开始
[AlphaEval] 因子 48/100 factor_048 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 48/100 factor_048 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 48/100 factor_048 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 48/100 factor_048 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 48/100 factor_048：完成，耗时=9.5s，总进度=48.0%，预计剩余=7.9min
[AlphaEval] 因子 49/100 factor_049：开始
[AlphaEval] 因子 49/100 factor_049 [1/4] IC/RankIC 完成 (3.0s)
[AlphaEval] 因子 49/100 factor_049 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 49/100 factor_049 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 49/100 factor_049 [4/4] 排名稳定性完成 (2.8s)
[AlphaEval] 因子 49/100 factor_049：完成，耗时=9.4s，总进度=49.0%，预计剩余=7.7min
[AlphaEval] 因子 50/100 factor_050：开始
[AlphaEval] 因子 50/100 factor_050 [1/4] IC/RankIC 完成 (3.3s)
[AlphaEval] 因子 50/100 factor_050 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 50/100 factor_050 [3/4] 扰动鲁棒性完成 (3.3s)
[AlphaEval] 因子 50/100 factor_050 [4/4] 排名稳定性完成 (2.9s)
[AlphaEval] 因子 50/100 factor_050：完成，耗时=10.1s，总进度=50.0%，预计剩余=7.6min
[AlphaEval] 因子 51/100 factor_051：开始
[AlphaEval] 因子 51/100 factor_051 [1/4] IC/RankIC 完成 (2.7s)
[AlphaEval] 因子 51/100 factor_051 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 51/100 factor_051 [3/4] 扰动鲁棒性完成 (2.7s)
[AlphaEval] 因子 51/100 factor_051 [4/4] 排名稳定性完成 (2.5s)
[AlphaEval] 因子 51/100 factor_051：完成，耗时=8.6s，总进度=51.0%，预计剩余=7.4min
[AlphaEval] 因子 52/100 factor_052：开始
[AlphaEval] 因子 52/100 factor_052 [1/4] IC/RankIC 完成 (2.5s)
[AlphaEval] 因子 52/100 factor_052 [2/4] Top组合 Sharpe 完成 (0.5s)
[AlphaEval] 因子 52/100 factor_052 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 52/100 factor_052 [4/4] 排名稳定性完成 (2.1s)
[AlphaEval] 因子 52/100 factor_052：完成，耗时=8.6s，总进度=52.0%，预计剩余=7.3min
[AlphaEval] 因子 53/100 factor_053：开始
[AlphaEval] 因子 53/100 factor_053 [1/4] IC/RankIC 完成 (2.3s)
[AlphaEval] 因子 53/100 factor_053 [2/4] Top组合 Sharpe 完成 (0.5s)
[AlphaEval] 因子 53/100 factor_053 [3/4] 扰动鲁棒性完成 (2.9s)
[AlphaEval] 因子 53/100 factor_053 [4/4] 排名稳定性完成 (2.0s)
[AlphaEval] 因子 53/100 factor_053：完成，耗时=7.9s，总进度=53.0%，预计剩余=7.1min
[AlphaEval] 因子 54/100 factor_054：开始
[AlphaEval] 因子 54/100 factor_054 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 54/100 factor_054 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 54/100 factor_054 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 54/100 factor_054 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 54/100 factor_054：完成，耗时=9.7s，总进度=54.0%，预计剩余=7.0min
[AlphaEval] 因子 55/100 factor_055：开始
[AlphaEval] 因子 55/100 factor_055 [1/4] IC/RankIC 完成 (2.7s)
[AlphaEval] 因子 55/100 factor_055 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 55/100 factor_055 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 55/100 factor_055 [4/4] 排名稳定性完成 (2.3s)
[AlphaEval] 因子 55/100 factor_055：完成，耗时=8.8s，总进度=55.0%，预计剩余=6.8min
[AlphaEval] 因子 56/100 factor_056：开始
[AlphaEval] 因子 56/100 factor_056 [1/4] IC/RankIC 完成 (2.3s)
[AlphaEval] 因子 56/100 factor_056 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 56/100 factor_056 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 56/100 factor_056 [4/4] 排名稳定性完成 (1.9s)
[AlphaEval] 因子 56/100 factor_056：完成，耗时=7.9s，总进度=56.0%，预计剩余=6.6min
[AlphaEval] 因子 57/100 factor_057：开始
[AlphaEval] 因子 57/100 factor_057 [1/4] IC/RankIC 完成 (2.9s)
[AlphaEval] 因子 57/100 factor_057 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 57/100 factor_057 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 57/100 factor_057 [4/4] 排名稳定性完成 (2.5s)
[AlphaEval] 因子 57/100 factor_057：完成，耗时=9.2s，总进度=57.0%，预计剩余=6.5min
[AlphaEval] 因子 58/100 factor_058：开始
[AlphaEval] 因子 58/100 factor_058 [1/4] IC/RankIC 完成 (2.9s)
[AlphaEval] 因子 58/100 factor_058 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 58/100 factor_058 [3/4] 扰动鲁棒性完成 (3.0s)
[AlphaEval] 因子 58/100 factor_058 [4/4] 排名稳定性完成 (2.6s)
[AlphaEval] 因子 58/100 factor_058：完成，耗时=9.1s，总进度=58.0%，预计剩余=6.3min
[AlphaEval] 因子 59/100 factor_059：开始
[AlphaEval] 因子 59/100 factor_059 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 59/100 factor_059 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 59/100 factor_059 [3/4] 扰动鲁棒性完成 (3.2s)
[AlphaEval] 因子 59/100 factor_059 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 59/100 factor_059：完成，耗时=9.6s，总进度=59.0%，预计剩余=6.2min
[AlphaEval] 因子 60/100 factor_060：开始
[AlphaEval] 因子 60/100 factor_060 [1/4] IC/RankIC 完成 (3.1s)
[AlphaEval] 因子 60/100 factor_060 [2/4] Top组合 Sharpe 完成 (0.4s)
[AlphaEval] 因子 60/100 factor_060 [3/4] 扰动鲁棒性完成 (3.1s)
[AlphaEval] 因子 60/100 factor_060 [4/4] 排名稳定性完成 (2.7s)
[AlphaEval] 因子 60/100 factor_060：完成，耗时=9.5s，总进度=60.0%，预计剩余=6.1min
[AlphaEval] 因子 61/100 factor_061：开始

NameError: name 'experiment_dir' is not defined

## 11. LightGBM 滚动融合

使用 purge 滚动训练。快速配置利用 2020–2023 年的因子和标签建立初始模型，只输出 2024–2026 年的 `prediction_score.csv` 供本地 RQAlphaPlus 回测；后续窗口只使用当时已经成熟的历史标签进行 walk-forward 更新。

In [ ]:
from src.model import LightGBMConfig, LightGBMFusion

fusion = LightGBMFusion(LightGBMConfig(**config['lightgbm']))
prediction = fusion.fit_predict(
    daily, factor_matrix, selected_factors, output_dir='results/lightgbm'
)
shutil.copy2('results/lightgbm/model_metrics.csv', experiment_dir / 'lgbm_model_metrics.csv')
prediction.to_csv(experiment_dir / 'prediction_score.csv', index=False)
loaded_lgbm = LightGBMFusion.load('results/lightgbm/lgbm_model.joblib')
print('LightGBM 模型重载成功；特征数:', len(loaded_lgbm['features']))
display(prediction.tail(30))

## 12. 打包并下载 Colab 训练产物

压缩包包含配置、GFlowNet 检查点、因子池、因子矩阵、AlphaEval 结果、LightGBM 模型与预测分数。下载后在本地仓库根目录解压，再运行 `notebooks/06_rqalpha_backtest.ipynb`。

In [ ]:
from google.colab import files
from zipfile import ZIP_DEFLATED, ZipFile

archive_entries = [
    (Path(CONFIG_PATH), 'results/colab_training_config.yaml'),
    (Path('checkpoints/gflownet_best.pt'), 'checkpoints/gflownet_best.pt'),
    (Path('results/data_quality_report.json'), 'results/data_quality_report.json'),
    (Path('results/gflownet_training_metrics.csv'), 'results/gflownet_training_metrics.csv'),
    (Path('results/gflownet_trajectory_metrics.csv'), 'results/gflownet_trajectory_metrics.csv'),
    (Path('results/alpha_pool.csv'), 'results/alpha_pool.csv'),
    (Path('results/alpha_factor_matrix.pkl'), 'results/alpha_factor_matrix.pkl'),
    (Path('results/alpha_factor_matrix_oos.pkl'), 'results/alpha_factor_matrix_oos.pkl'),
    (Path('results/alpha_eval_result.csv'), 'results/alpha_eval_result.csv'),
    (Path('results/lightgbm/lgbm_model.joblib'), 'results/lightgbm/lgbm_model.joblib'),
    (Path('results/lightgbm/model_metrics.csv'), 'results/lightgbm/model_metrics.csv'),
    (Path('results/lightgbm/feature_importance.csv'), 'results/lightgbm/feature_importance.csv'),
    (Path('results/lightgbm/prediction_score.csv'), 'results/lightgbm/prediction_score.csv'),
]
missing_outputs = [str(path) for path, _ in archive_entries if not path.exists()]
if missing_outputs:
    raise FileNotFoundError(f'缺少训练产物: {missing_outputs}')

archive_path = Path('/content/alphamining_colab_outputs.zip')
with ZipFile(archive_path, 'w', ZIP_DEFLATED) as archive:
    for path, archive_name in archive_entries:
        archive.write(path, arcname=archive_name)
print('产物压缩包:', archive_path, '大小（MB）:', round(archive_path.stat().st_size / 1024**2, 2))
print('本地回测入口: notebooks/06_rqalpha_backtest.ipynb')
if DOWNLOAD_OUTPUTS:
    files.download(str(archive_path))